name: Upload Website

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_Bucket }}
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_Access_Key}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_Access_Secret}}
        AWS_REGION: 'us-east-2'   # optional: defaults to us-east-1
        SOURCE_DIR: './'      # optional: defaults to entire repository