name: ReleaseCI
on: [pull_request,push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Release to S3
      run: bash scripts/pipeline/release.sh 'oliver-otcheres-test-bucket' "folder1" ${{secrets.AWS_Access_Key}} ${{secrets.AWS_Access_Secret}} "myapp"